debug: false

# Clock settings
clock_interval: 20

# World climate settings
random_weather: true # Can be changed during runtime
stability: 20000
sky_light_sunny: 12
block_light_heated: 10

# Player settings
base_bodily_regulation: 0.03
heating_from_work: 0.03
max_hydration: 600
water_bottle_hydration: 120
max_wetness: 400
sweating:
  hydration_cost: 5
  wetness_bonus: 20

# Bodily Conditions
severe_hypothermia_degrees_C: 28
hypothermia_degrees_C: 35
comfort_min_C: 37
comfort_max_C: 37.5
hyperthermia_degrees_C: 38.3
severe_hyperthermia_degrees_C: 40

# Extremes settings
heatwave:
  base_degree_change_when_exposed: 0.03
  severity: 1000
  minimum_duration: 3600
  maximum_duration: 10000
coldsnap:
  base_degree_change_when_exposed: 0.02
  severity: 500
  minimum_duration: 2000
  maximum_duration: 10000
